// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnK1HExEuB3OHSNGFMH53CN3zEjVBiybY',
    appId: '1:149253441126:android:728518dd81568a0a12cfa7',
    messagingSenderId: '149253441126',
    projectId: 'outdoor-traveler',
    databaseURL: 'https://outdoor-traveler-default-rtdb.firebaseio.com',
    storageBucket: 'outdoor-traveler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCdAhWW8F-ryy3elwsY80ryJ02UiYsOI',
    appId: '1:149253441126:ios:ad1da62bfeb6032e12cfa7',
    messagingSenderId: '149253441126',
    projectId: 'outdoor-traveler',
    databaseURL: 'https://outdoor-traveler-default-rtdb.firebaseio.com',
    storageBucket: 'outdoor-traveler.appspot.com',
    iosClientId:
        '149253441126-89c2i9kv2pofj2pn7ovct8aajl6tn3h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangoutApp',
  );
}
